apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.5.0"           
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  interval: 5m
  values:
    grafana:
      enabled: false         
    alertmanager:
      enabled: false         
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
  
